export const AnnouncementList = [{
    "title": "First Explore Business Careers for Engineers",
    "itemUrl": "",
    "body": "Your technical expertise puts you ahead of the curve in the value chain of the global economy.",
    "contentTypeName": "Article",
    "educationType": " graduate education management",
    "author": "Joe Smith",
    "publishDate": " 2017-04-27T08:46:00Z",
    "largeImage": "/MBAWeb/Assets/img/topic_hero1.png",
    "smallImage": "Alt tag",
    "eventDate": " 2017-04-27T08:46:00Z",
    "thumbnailImageUrl": " -/media/Experience-Explorer/Presets/Chris-128x128.ashx",
    "schoolTagName": ["Harvard"],
    "topicTagName": ["Military", "Engineering"]
}, {
    "title": "First Explore Business Careers for Engineers",
    "itemUrl": "",
    "body": "Your technical expertise puts you ahead of the curve in the value chain of the global economy.",
    "contentTypeName": "Article1",
    "educationType": " graduate education management",
    "author": "Joe Smith",
    "publishDate": " 2017-04-27T08:46:00Z",
    "largeImage": "/MBAWeb/Assets/img/topic_hero1.png",
    "smallImage": "Alt tag",
    "eventDate": " 2017-04-27T08:46:00Z",
    "thumbnailImageUrl": " -/media/Experience-Explorer/Presets/Chris-128x128.ashx",
    "schoolTagName": ["Harvard"],
    "topicTagName": ["Military", "Engineering"]
}, {
    "title": "First Explore Business Careers for Engineers",
    "itemUrl": "",
    "body": "Your technical expertise puts you ahead of the curve in the value chain of the global economy.",
    "contentTypeName": "Article2",
    "educationType": " graduate education management",
    "author": "Joe Smith",
    "publishDate": " 2017-04-27T08:46:00Z",
    "largeImage": "/MBAWeb/Assets/img/topic_hero1.png",
    "smallImage": "Alt tag",
    "eventDate": " 2017-04-27T08:46:00Z",
    "thumbnailImageUrl": " -/media/Experience-Explorer/Presets/Chris-128x128.ashx",
    "schoolTagName": ["Harvard"],
    "topicTagName": ["Military", "Engineering"]
}, {
    "title": "First Explore Business Careers for Engineers",
    "itemUrl": "",
    "body": "Your technical expertise puts you ahead of the curve in the value chain of the global economy.",
    "contentTypeName": "Article3",
    "educationType": " graduate education management",
    "author": "Joe Smith",
    "publishDate": " 2017-04-27T08:46:00Z",
    "largeImage": "/MBAWeb/Assets/img/topic_hero1.png",
    "smallImage": "Alt tag",
    "eventDate": " 2017-04-27T08:46:00Z",
    "thumbnailImageUrl": " -/media/Experience-Explorer/Presets/Chris-128x128.ashx",
    "schoolTagName": ["Harvard"],
    "topicTagName": ["Military", "Engineering"]
}, {
    "title": "First Explore Business Careers for Engineers",
    "itemUrl": "",
    "body": "Your technical expertise puts you ahead of the curve in the value chain of the global economy.",
    "contentTypeName": "Article4",
    "educationType": " graduate education management",
    "author": "Joe Smith",
    "publishDate": " 2017-04-27T08:46:00Z",
    "largeImage": "/MBAWeb/Assets/img/topic_hero1.png",
    "smallImage": "Alt tag",
    "eventDate": " 2017-04-27T08:46:00Z",
    "thumbnailImageUrl": " -/media/Experience-Explorer/Presets/Chris-128x128.ashx",
    "schoolTagName": ["Harvard"],
    "topicTagName": ["Military", "Engineering"]
}, {
    "title": "First Explore Business Careers for Engineers",
    "itemUrl": "",
    "body": "Your technical expertise puts you ahead of the curve in the value chain of the global economy.",
    "contentTypeName": "Article5",
    "educationType": " graduate education management",
    "author": "Joe Smith",
    "publishDate": " 2017-04-27T08:46:00Z",
    "largeImage": "/MBAWeb/Assets/img/topic_hero1.png",
    "smallImage": "Alt tag",
    "eventDate": " 2017-04-27T08:46:00Z",
    "thumbnailImageUrl": " -/media/Experience-Explorer/Presets/Chris-128x128.ashx",
    "schoolTagName": ["Harvard"],
    "topicTagName": ["Military", "Engineering"]
}, {
    "title": "First Explore Business Careers for Engineers",
    "itemUrl": "",
    "body": "Your technical expertise puts you ahead of the curve in the value chain of the global economy.",
    "contentTypeName": "Article6",
    "educationType": " graduate education management",
    "author": "Joe Smith",
    "publishDate": " 2017-04-27T08:46:00Z",
    "largeImage": "/MBAWeb/Assets/img/topic_hero1.png",
    "smallImage": "Alt tag",
    "eventDate": " 2017-04-27T08:46:00Z",
    "thumbnailImageUrl": " -/media/Experience-Explorer/Presets/Chris-128x128.ashx",
    "schoolTagName": ["Harvard"],
    "topicTagName": ["Military", "Engineering"]
}, {
    "title": "How did your military experience help you stand out as a business school applicant?",
    "itemUrl": " /en/sitecore/shell/mbas-and-management-education/articles/article",
    "body": "What an MBA offers you is the opportunity to transition into a new community, to build your business skills while capitalizing on the leadership ",
    "contentTypeName": "Article7",
    "educationType": " graduate education management",
    "author": "Louis Rodrigues",
    "publishDate": " 2014-23-27T08:46:00Z",
    "largeImage": "/MBAWeb/Assets/img/topic_hero2.png",
    "smallImage": "/MBAWeb/Assets/img/topic_hero2.png",
    "eventDate": " 2017-04-27T08:46:00Z",
    "thumbnailImageUrl": " -/media/Experience-Explorer/Presets/Chris-128x128.ashx",
    "schoolTagName": ["Harvard"],
    "topicTagName": ["Military", "Engineering"]
}, {
    "title": "The value of a Business Degree in Four Steps",
    "itemUrl": " /en/sitecore/shell/mbas-and-management-education/articles/article",
    "body": "Before we look at how to calculate your ROI, keep in mind the potential benefits of an MBA *92% of 2012 graduates surveyed by GMAC® were employed three months after graduation *77% said their starting salary met or exceeded their expectations *76% said they could not have gotten their job without their MBA",
    "contentTypeName": "Article8",
    "educationType": " graduate education management",
    "author": "Joseph Day",
    "publishDate": " 2015-05-27T08:46:00Z",
    "largeImage": "assets/apply.jpg",
    "smallImage": "Alt tag",
    "eventDate": " 2017-04-27T08:46:00Z",
    "thumbnailImageUrl": " -/media/Experience-Explorer/Presets/Chris-128x128.ashx",
    "schoolTagName": ["Harvard"],
    "topicTagName": ["Military", "Engineering"]
}];