export const eventDetailSample = {
    description: 'Come hear about our Full-Time MBA program from staff and GSB alumni.',
    phoneNumber: '6574893',
    startDate: '',
    activeFlag: 0,
    endDate: '',
    websiteAddress: 'http://gsb.uchicago.edu/static.asp?nNodeId=80 ',
    codeIdStartHour: '',
    codeIdEndHour: '',
    address1: 'ad1',
    address2: '',
    address3: '',
    city: '',
    stateProvonceId: 0,
    countryId: 0,
    emailAddress: 'admissions@gsb.uchicago.edu',
    registrationRequired: "Yes",
    hostNames: ['school1', 'school2', 'school3'],
    isOnLine: false,
    eventStateName: '',
    eventEmail: '',
    eventCountryName: '',
    eventCityName: '',
    eventPostalCode: ''
};
